apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-role-privileged
  namespace: kube-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames: ['k8s.privileged']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-privileged-role-binding
  namespace: kube-system
roleRef:
  kind: Role
  name: psp-role-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:kube-system
  namespace: kube-system

